from . import pharmacy
from . import account_invoice
from . import supplier_discount
from . import credit_limit
from . import partner_payment
from . import rack_transfer
from . import partial_transfer
from . import res_partner
from . import product
from . import cheque
from . import stockpicking
from . import enquiry
from . import stock_view_and_order
from . import master_bank
from . import cash_and_expense_book
from . import expense_book
from . import account_voucher
from . import customer_invoice_wizard
from . import create_order
from .import supplier_invoice_wizard_form
from . import home_page
from . import stock_search_expiry
from . import password_authentication
from . import payment_page_password_validation